/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import controller.ctr_AcceuilleAutreProduit;
import java.security.Principal;
import javax.swing.JButton;
import javax.swing.JScrollPane;

/**
 *
 * @author Mr_JYPY
 */
public class AcceuilleAutreProduit extends javax.swing.JPanel {
private Principal pcp;
private ctr_AcceuilleAutreProduit ctr;
    /**
     * Creates new form AcceuilleAutreProduit
     */
     private static AcceuilleAutreProduit instance=null;
   private AcceuilleAutreProduit() {
     //   this.pcp=pcp;
       initComponents();
       ctr=new ctr_AcceuilleAutreProduit(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        effectuerEntree = new javax.swing.JButton();
        effectuerSortie = new javax.swing.JButton();
        divers = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        etatGlobal = new javax.swing.JButton();
        btnFamille = new javax.swing.JButton();
        SrolpanelAutreProduit = new javax.swing.JScrollPane();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setText("   GESTION DES AUTRES ARTICLES");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 51), new java.awt.Color(204, 51, 0), new java.awt.Color(204, 255, 255), new java.awt.Color(204, 0, 255)));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Differentes Options", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(153, 0, 0))); // NOI18N

        effectuerEntree.setBackground(new java.awt.Color(255, 255, 204));
        effectuerEntree.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        effectuerEntree.setForeground(new java.awt.Color(102, 51, 0));
        effectuerEntree.setText("Enregister une Entrée");

        effectuerSortie.setBackground(new java.awt.Color(53, 78, 29));
        effectuerSortie.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        effectuerSortie.setText("Enregister une Sortie");
        effectuerSortie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                effectuerSortieActionPerformed(evt);
            }
        });

        divers.setBackground(new java.awt.Color(204, 204, 204));
        divers.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        divers.setForeground(new java.awt.Color(51, 0, 51));
        divers.setText("Divers");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bilan des Entree Sortie", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(51, 0, 0))); // NOI18N

        etatGlobal.setBackground(new java.awt.Color(204, 255, 204));
        etatGlobal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        etatGlobal.setForeground(new java.awt.Color(102, 51, 0));
        etatGlobal.setText("Etat Global");
        etatGlobal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etatGlobalActionPerformed(evt);
            }
        });

        btnFamille.setBackground(new java.awt.Color(255, 204, 204));
        btnFamille.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnFamille.setForeground(new java.awt.Color(82, 82, 54));
        btnFamille.setText("Par Famille");
        btnFamille.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etatGlobal, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnFamille, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFamille, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etatGlobal, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(effectuerEntree)
                .addGap(29, 29, 29)
                .addComponent(effectuerSortie, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(divers, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(199, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 28, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(effectuerEntree, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(effectuerSortie, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(divers, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SrolpanelAutreProduit.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Differentes Opérations", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(51, 51, 0))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SrolpanelAutreProduit)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(330, 330, 330)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SrolpanelAutreProduit, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void etatGlobalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etatGlobalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etatGlobalActionPerformed

    private void effectuerSortieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_effectuerSortieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_effectuerSortieActionPerformed

   public static AcceuilleAutreProduit getInstance()
        {
           if(instance==null)
           {
             instance=new AcceuilleAutreProduit();
           }
           return instance;
        }
     public static void SetNull(){
         instance=null;
     }

    public static JScrollPane getSrolpanelAutreProduit() {
        return SrolpanelAutreProduit;
    }

    public static void setSrolpanelAutreProduit(JScrollPane SrolpanelAutreProduit) {
        AcceuilleAutreProduit.SrolpanelAutreProduit = SrolpanelAutreProduit;
    }

    public static JButton getDivers() {
        return divers;
    }

    public static void setDivers(JButton divers) {
        AcceuilleAutreProduit.divers = divers;
    }

    public static JButton getEffectuerEntree() {
        return effectuerEntree;
    }

    public static void setEffectuerEntree(JButton effectuerEntree) {
        AcceuilleAutreProduit.effectuerEntree = effectuerEntree;
    }

    public static JButton getEffectuerSortie() {
        return effectuerSortie;
    }

    public static void setEffectuerSortie(JButton effectuerSortie) {
        AcceuilleAutreProduit.effectuerSortie = effectuerSortie;
    }

    public static JButton getEtatGlobal() {
        return etatGlobal;
    }

    public  JButton getBtnFamille() {
        return btnFamille;
    }

    public static void setEtatGlobal(JButton etatGlobal) {
        AcceuilleAutreProduit.etatGlobal = etatGlobal;
    }
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JScrollPane SrolpanelAutreProduit;
    private javax.swing.JButton btnFamille;
    public static javax.swing.JButton divers;
    public static javax.swing.JButton effectuerEntree;
    public static javax.swing.JButton effectuerSortie;
    public static javax.swing.JButton etatGlobal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
