/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import classe.OperationProductionProduitFini;
import classe.venteProduitFini;
import com.toedter.calendar.JDateChooser;
import controller.ctr_contenuEntreeMatierePremiere;
import controller.ctr_contenuProduction;
import controller.ctr_contenuVente;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import model.md_contenuVente;

/**
 *
 * @author Mr_JYPY
 */
public class ContenuVente extends javax.swing.JPanel {

    /**
     * Creates new form ContenuRetour
     */
    ctr_contenuVente ctr;
    public ContenuVente() {
        initComponents();
        String sql="SELECT CONCAT(nom,CONCAT(' ',prenom)) as designation "
                + "FROM `personnel` WHERE service=(SELECT id FROM services WHERE abreviation='COM') AND "
                + "fonction='RESPONSABLE DISTRIBUTEUR INTERNE'";
         String sqlcLIENTS="SELECT nom as designation FROM clients";
            String sqlMagasin="SELECT stocks_magasin_produit_fini.id,magasin.designation\n" +
"FROM stocks_magasin_produit_fini\n" +
"INNER JOIN magasin ON magasin.id=stocks_magasin_produit_fini.magasin AND magasin.type='cartonMc'\n" +
"WHERE stocks_magasin_produit_fini.quantite>0";  
        ctr_contenuEntreeMatierePremiere.remplirItem(magasin, sqlMagasin);
        ctr_contenuEntreeMatierePremiere.remplirItem(listeRDI, sql);
        ctr_contenuEntreeMatierePremiere.remplirItem(listeClient, sqlcLIENTS);
        ctr_contenuEntreeMatierePremiere.MettreDate(dateActuelle);
         //demarrage du controlleur
          ctr=new ctr_contenuVente(this);
          /*
          partie pour initialiser les Jtable
          */
           String sql2="SELECT vente_produit_fini.id,vente_produit_fini.dateString,vente_produit_fini.bordereaux,vente_produit_fini.quantite,vente_produit_fini.stocks_avant,\n" +
" vente_produit_fini.stocks_apres,personnel.id as idP,personnel.nom as nomP ,personnel.prenom as prenomP,\n" +
" clients.nom as nomC ,clients.id as idC FROM`vente_produit_fini`\n" +
" INNER JOIN clients ON clients.id=vente_produit_fini.client "
+ " INNER JOIN personnel ON personnel.id=vente_produit_fini.personnel \n" +
" WHERE vente_produit_fini.date=CURRENT_DATE() ORDER BY vente_produit_fini.date DESC";
           //System.out.println("Liste des ventes actuelles : "+md_contenuVente.listeDesVentes(sql2));
          String sqlAll="SELECT vente_produit_fini.id,vente_produit_fini.dateString,vente_produit_fini.bordereaux,vente_produit_fini.quantite,vente_produit_fini.stocks_avant,\n" +
" vente_produit_fini.stocks_apres,personnel.id as idP,personnel.nom as nomP ,personnel.prenom as prenomP,\n" +
" clients.nom as nomC ,clients.id as idC FROM`vente_produit_fini`\n" +
" INNER JOIN clients ON clients.id=vente_produit_fini.client "
+ " INNER JOIN personnel ON personnel.id=vente_produit_fini.personnel \n" +
" WHERE 1 ORDER BY vente_produit_fini.date DESC";
           ArrayList<venteProduitFini> liste=md_contenuVente.listeDesVentes(sql2);
           ArrayList<venteProduitFini> listeAll=md_contenuVente.listeDesVentes(sqlAll);
           DefaultTableModel model=( DefaultTableModel) JtableAuj.getModel();
           DefaultTableModel modelAll=( DefaultTableModel) JtableAll.getModel();
           if(liste.size()>0)
           {
         ctr_contenuVente.AfficherDansTableModel(liste, model,liste.get(0));
           }
           if(listeAll.size()>0)
           {
           ctr_contenuVente.AfficherDansTableModel(listeAll, modelAll,listeAll.get(0));
           }
           //creation des elements
        OperationProductionProduitFini op=new OperationProductionProduitFini("vente_produit_fini");
        ArrayList<OperationProductionProduitFini> listeBilan=ctr_contenuProduction.genererBilan("vente_produit_fini");
            DefaultTableModel modelBilan=( DefaultTableModel) JtableBilan.getModel();
              if(listeBilan.size()>0){
         ctr_contenuProduction.AfficherDansTableModel(listeBilan, modelBilan,listeBilan.get(0));
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        dateActuelle = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        autreDate = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        magasin = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        quantite = new javax.swing.JSpinner();
        validerVente = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        libelle = new javax.swing.JTextField();
        genererbordereaux = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        listeRDI = new javax.swing.JComboBox();
        listeClient = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JtableAuj = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JtableAll = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        JtableBilan = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Remplissez  Correctement les Champs", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(51, 51, 0))); // NOI18N

        jLabel2.setText("  Date");

        dateActuelle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dateActuelle.setForeground(new java.awt.Color(102, 51, 0));

        jLabel4.setText("Autre Date");

        autreDate.setDateFormatString("dd MMMM yyyy");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setText("Magasin");

        magasin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        magasin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Aucun choix" }));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 0, 0));
        jLabel6.setText("Quantite");

        quantite.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        validerVente.setBackground(new java.awt.Color(102, 102, 0));
        validerVente.setText("Enregister");
        validerVente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 51, 51)));

        jLabel7.setText("Bordereaux");

        libelle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        genererbordereaux.setText("...");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 0));
        jLabel3.setText("RDI");

        listeRDI.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Aucun choix" }));

        listeClient.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Aucun choix" }));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 0, 0));
        jLabel10.setText("Clients");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(dateActuelle, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(autreDate, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(quantite)
                            .addComponent(magasin, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(genererbordereaux))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(libelle, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(listeRDI, 0, 232, Short.MAX_VALUE)
                            .addComponent(listeClient, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(346, 346, 346)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(validerVente, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(246, 246, 246))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(dateActuelle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(magasin, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(autreDate, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(quantite, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(libelle, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(listeRDI))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(genererbordereaux, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(listeClient))
                .addGap(12, 12, 12)
                .addComponent(validerVente, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        JtableAuj.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N°", "Qte", "Stocks_avant", "Stocks_apres", "Bordereaux", "Rdi", "Client"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(JtableAuj);
        if (JtableAuj.getColumnModel().getColumnCount() > 0) {
            JtableAuj.getColumnModel().getColumn(0).setMinWidth(30);
            JtableAuj.getColumnModel().getColumn(0).setMaxWidth(35);
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 0));
        jLabel1.setText("ENREGISTER UNE VENTE");

        JtableAll.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N°", "Date", "Quantiter", "Stocks_avant", "Stocks_apres", "bordereaux", "RDI", "Client"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(JtableAll);
        if (JtableAll.getColumnModel().getColumnCount() > 0) {
            JtableAll.getColumnModel().getColumn(0).setMinWidth(30);
            JtableAll.getColumnModel().getColumn(0).setMaxWidth(35);
        }

        JtableBilan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Quantite/Periode", "Jour", "Semaine", "Mois", "Stocks"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(JtableBilan);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Tous Les Ventes Enregistres");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("               Total  Vente Par Periode");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
                    .addComponent(jScrollPane3)))
            .addGroup(layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
            .addGroup(layout.createSequentialGroup()
                .addGap(447, 447, 447)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(8, 8, 8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(9, 9, 9))
        );
    }// </editor-fold>//GEN-END:initComponents

    public JComboBox getListeClient() {
        return listeClient;
    }

    public void setListeClient(JComboBox AgentsDistributions) {
        this.listeClient = AgentsDistributions;
    }

    public JComboBox getListeRDI() {
        return listeRDI;
    }

    public JDateChooser getAutreDate() {
        return autreDate;
    }

    public void setAutreDate(JDateChooser autreDate) {
        this.autreDate = autreDate;
    }

    public void setListeRDI(JComboBox listeRDI) {
        this.listeRDI = listeRDI;
    }

    public JComboBox getMagasin() {
        return magasin;
    }

    public void setMagasin(JComboBox magasin) {
        this.magasin = magasin;
    }

    public JSpinner getQuantite() {
        return quantite;
    }

    public void setQuantite(JSpinner quantite) {
        this.quantite = quantite;
    }

    public JButton getValiderVente() {
        return validerVente;
    }

    public void setValiderVente(JButton validerVente) {
        this.validerVente = validerVente;
    }

    public JTable getJtableAll() {
        return JtableAll;
    }

    public void setJtableAll(JTable JtableAll) {
        this.JtableAll = JtableAll;
    }

    public JTable getJtableAuj() {
        return JtableAuj;
    }

    public void setJtableAuj(JTable JtableAuj) {
        this.JtableAuj = JtableAuj;
    }

    public JTable getJtableBilan() {
        return JtableBilan;
    }

    public void setJtableBilan(JTable JtableBilan) {
        this.JtableBilan = JtableBilan;
    }

    public JLabel getDateActuelle() {
        return dateActuelle;
    }

    public void setDateActuelle(JLabel dateActuelle) {
        this.dateActuelle = dateActuelle;
    }

    public JButton getGenererbordereaux() {
        return genererbordereaux;
    }

    public void setGenererbordereaux(JButton genererbordereaux) {
        this.genererbordereaux = genererbordereaux;
    }

    public JTextField getLibelle() {
        return libelle;
    }

    public void setLibelle(JTextField libelle) {
        this.libelle = libelle;
    }

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JtableAll;
    private javax.swing.JTable JtableAuj;
    private javax.swing.JTable JtableBilan;
    private com.toedter.calendar.JDateChooser autreDate;
    private javax.swing.JLabel dateActuelle;
    private javax.swing.JButton genererbordereaux;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField libelle;
    private javax.swing.JComboBox listeClient;
    private javax.swing.JComboBox listeRDI;
    private javax.swing.JComboBox magasin;
    private javax.swing.JSpinner quantite;
    private javax.swing.JButton validerVente;
    // End of variables declaration//GEN-END:variables
}
