/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import classe.OperationProductionProduitFini;
import classe.retourProduit;
import com.toedter.calendar.JDateChooser;
import controller.ctr_contenuEntreeMatierePremiere;
import controller.ctr_contenuProduction;
import controller.ctr_contenuRetour;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import model.md_contenuRetour;
import model.md_contenuSortieMatierePremiere;

/**
 *
 * @author Mr_JYPY
 */
public class ContenuRetour extends javax.swing.JPanel {

    /**
     * Creates new form ContenuRetour
     */
    private ctr_contenuRetour ctr;
    public ContenuRetour() {
        initComponents();
        String sql="SELECT CONCAT(nom,CONCAT(' ',prenom)) as designation "
                + "FROM `personnel` WHERE service=(SELECT id FROM services WHERE abreviation='COM') AND "
                + "fonction='RESPONSABLE DISTRIBUTEUR INTERNE'";
         String sqlcLIENTS="SELECT nom as designation FROM clients";
            String sqlMagasin="SELECT designation FROM magasin WHERE type='cartonMc'";  
        ctr_contenuEntreeMatierePremiere.remplirItem(magasin, sqlMagasin);
        ctr_contenuEntreeMatierePremiere.remplirItem(listeRDI, sql);
        ctr_contenuEntreeMatierePremiere.MettreDate(dateActuelle);
         String bor=md_contenuSortieMatierePremiere.genererUnBordereauxLivraison("retour_produit_fini","bordereaux","Rtr","Mc");
       ctr_contenuEntreeMatierePremiere.remplirItem(libelle, bor, 0);
       ctr=new ctr_contenuRetour(this);
       /*
        *partie pour initialiser les JtableModel
        */
           String sql2="SELECT retour_produit_fini.id,retour_produit_fini.dateString,retour_produit_fini.bordereaux,retour_produit_fini.quantite,retour_produit_fini.stocks_avant,\n" +
" retour_produit_fini.stocks_apres,personnel.id as idP,personnel.nom as nomP ,personnel.prenom as prenomP,\n" +
" magasin.designation as designationM,magasin.id as idM FROM `retour_produit_fini`\n" +
 " INNER JOIN personnel ON personnel.id=retour_produit_fini.personnel \n"
 + " INNER JOIN magasin ON magasin.id=retour_produit_fini.magasin" +
" WHERE retour_produit_fini.date=CURRENT_DATE() ORDER BY retour_produit_fini.date DESC";
           //System.out.println("Liste des ventes actuelles : "+md_contenuVente.listeDesVentes(sql2));
          String sqlAll="SELECT retour_produit_fini.id,retour_produit_fini.dateString,retour_produit_fini.bordereaux,retour_produit_fini.quantite,retour_produit_fini.stocks_avant,\n" +
" retour_produit_fini.stocks_apres,personnel.id as idP,personnel.nom as nomP ,personnel.prenom as prenomP,\n" +
" magasin.designation as designationM,magasin.id as idM FROM `retour_produit_fini`\n" +
 " INNER JOIN personnel ON personnel.id=retour_produit_fini.personnel \n"
 + " INNER JOIN magasin ON magasin.id=retour_produit_fini.magasin" +
" WHERE 1 ORDER BY retour_produit_fini.date DESC";
          //System.out.println(sql2);
           ArrayList<retourProduit> liste=md_contenuRetour.listeDesReTourProduits(sql2);
           ArrayList<retourProduit> listeAll=md_contenuRetour.listeDesReTourProduits(sqlAll);
           DefaultTableModel model=( DefaultTableModel) JtableAuj.getModel();
           DefaultTableModel modelAll=( DefaultTableModel) JtableAll.getModel();
            ArrayList<OperationProductionProduitFini> listeBilan=ctr_contenuProduction.genererBilan("retour_produit_fini");
             DefaultTableModel modelBilan=( DefaultTableModel) JtableBilan.getModel();
           if(liste.size()>0){
         ctr_contenuRetour.AfficherDansTableModel(liste, model,liste.get(0));
            }
           if(listeAll.size()>0){
         ctr_contenuRetour.AfficherDansTableModel(listeAll, modelAll,listeAll.get(0));
            }
          if(listeBilan.size()>0){
         ctr_contenuRetour.AfficherDansTableModel(listeBilan,modelBilan,listeBilan.get(0));
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        dateActuelle = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        autreDate = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        magasin = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        quantite = new javax.swing.JSpinner();
        validerRetour = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        libelle = new javax.swing.JTextField();
        genererbordereaux = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        listeRDI = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        JtableAuj = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JtableAll = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        JtableBilan = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Remplissez  Correctement les Champs", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(51, 51, 0))); // NOI18N

        jLabel2.setText("  Date");

        dateActuelle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dateActuelle.setForeground(new java.awt.Color(102, 51, 0));

        jLabel4.setText("Autre Date");

        autreDate.setDateFormatString("dd MMMM yyyy");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setText("Magasin");

        magasin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        magasin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Aucun choix" }));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 0, 0));
        jLabel6.setText("Quantite");

        validerRetour.setBackground(new java.awt.Color(51, 51, 0));
        validerRetour.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        validerRetour.setText("Enregister");

        jLabel7.setText("Bordereaux");

        libelle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        genererbordereaux.setText("...");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 0));
        jLabel3.setText("RDI");

        listeRDI.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Aucun choix" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(dateActuelle, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(autreDate, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(quantite)
                            .addComponent(magasin, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(genererbordereaux))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(libelle, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(9, 9, Short.MAX_VALUE)
                        .addComponent(listeRDI, 0, 241, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(validerRetour, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(233, 233, 233))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(dateActuelle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(magasin, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(autreDate, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(quantite, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(21, 21, 21))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(libelle, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(listeRDI, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(genererbordereaux, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(validerRetour, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        JtableAuj.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N°", "Quantite", "Stocks_avant", "Stocks_apres", "Bordereaux", "Comm."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(JtableAuj);
        if (JtableAuj.getColumnModel().getColumnCount() > 0) {
            JtableAuj.getColumnModel().getColumn(0).setMinWidth(30);
            JtableAuj.getColumnModel().getColumn(0).setMaxWidth(35);
        }

        jLabel1.setBackground(new java.awt.Color(153, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("ENREGISTER UN RETOUR");

        JtableAll.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N°", "Date", "Quantiter", "Stocks_avant", "Stocks_apres", "Magasin", "Libelle", "Nom Com."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(JtableAll);
        if (JtableAll.getColumnModel().getColumnCount() > 0) {
            JtableAll.getColumnModel().getColumn(0).setMinWidth(30);
            JtableAll.getColumnModel().getColumn(0).setMaxWidth(35);
        }

        JtableBilan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Quantite/Periode", "Jour", "Semaine", "Mois", "Stocks"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(JtableBilan);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Tous Les Retour Enregistres");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("               Total Retours Par Periode");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 153, 0));
        jLabel10.setText("             Aujourd'hui");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(468, 468, 468))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(8, 8, 8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    public JTextField getLibelle() {
        return libelle;
    }

    public void setLibelle(JTextField libelle) {
        this.libelle = libelle;
    }

    public JTable getJtableAll() {
        return JtableAll;
    }

    public void setJtableAll(JTable JtableAll) {
        this.JtableAll = JtableAll;
    }

    public JTable getJtableAuj() {
        return JtableAuj;
    }

    public void setJtableAuj(JTable JtableAuj) {
        this.JtableAuj = JtableAuj;
    }

    public JTable getJtableBilan() {
        return JtableBilan;
    }

    public void setJtableBilan(JTable JtableBilan) {
        this.JtableBilan = JtableBilan;
    }

    public JDateChooser getAutreDate() {
        return autreDate;
    }

    public void setAutreDate(JDateChooser autreDate) {
        this.autreDate = autreDate;
    }

    public JLabel getDateActuelle() {
        return dateActuelle;
    }

    public void setDateActuelle(JLabel dateActuelle) {
        this.dateActuelle = dateActuelle;
    }

    public JButton getGenererbordereaux() {
        return genererbordereaux;
    }

    public void setGenererbordereaux(JButton genererbordereaux) {
        this.genererbordereaux = genererbordereaux;
    }

    public JComboBox getListeRDI() {
        return listeRDI;
    }

    public void setListeRDI(JComboBox listeRDI) {
        this.listeRDI = listeRDI;
    }

    public JComboBox getMagasin() {
        return magasin;
    }

    public void setMagasin(JComboBox magasin) {
        this.magasin = magasin;
    }

    public JSpinner getQuantite() {
        return quantite;
    }

    public void setQuantite(JSpinner quantite) {
        this.quantite = quantite;
    }

    public JButton getValiderRetour() {
        return validerRetour;
    }

    public void setValiderRetour(JButton validerRetour) {
        this.validerRetour = validerRetour;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JtableAll;
    private javax.swing.JTable JtableAuj;
    private javax.swing.JTable JtableBilan;
    private com.toedter.calendar.JDateChooser autreDate;
    private javax.swing.JLabel dateActuelle;
    private javax.swing.JButton genererbordereaux;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField libelle;
    private javax.swing.JComboBox listeRDI;
    private javax.swing.JComboBox magasin;
    private javax.swing.JSpinner quantite;
    private javax.swing.JButton validerRetour;
    // End of variables declaration//GEN-END:variables
}
