/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import classe.EntreeProduit;
import classe.OperationProductionProduitFini;
import com.toedter.calendar.JDateChooser;
import controller.ctr_contenuProduction;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import model.md_contenuProduction;

/**
 *
 * @author Mr_JYPY
 */
public class ContenuProduction extends javax.swing.JPanel {

    /**
     * Creates new form contenuProduction
     */
      private ctr_contenuProduction ctr;
      public ContenuProduction() {
        initComponents();
       ctr=new ctr_contenuProduction(this);

         //les requetes pour afficher dans les Jtable
      String sql2="SELECT entree_produit_fini.id,entree_produit_fini.dateString,entree_produit_fini.bordereaux,entree_produit_fini.quantite,entree_produit_fini.stocks_avant,\n" +
      " entree_produit_fini.stocks_apres,\n" +
         " magasin.id as idM,magasin.designation as nomMag\n" +
     " FROM `entree_produit_fini`\n" +
  " INNER JOIN magasin ON magasin.id=entree_produit_fini.magasin\n" +
  " WHERE entree_produit_fini.date=CURRENT_DATE() AND entree_produit_fini.type='PRODUCTION' ORDER BY entree_produit_fini.date DESC";
          String sqlAll="SELECT entree_produit_fini.id,entree_produit_fini.dateString,entree_produit_fini.bordereaux,entree_produit_fini.quantite,entree_produit_fini.stocks_avant,\n" +
      " entree_produit_fini.stocks_apres,\n" +
         " magasin.id as idM,magasin.designation as nomMag\n" +
     " FROM `entree_produit_fini`\n" +
  " INNER JOIN magasin ON magasin.id=entree_produit_fini.magasin\n" +
  " WHERE entree_produit_fini.type='PRODUCTION' ORDER BY entree_produit_fini.date DESC";
       ArrayList<EntreeProduit> liste=md_contenuProduction.donnerListeEntreeProduitFini(sql2);
       ArrayList<EntreeProduit> listeAll=md_contenuProduction.donnerListeEntreeProduitFini(sqlAll);
        ArrayList<OperationProductionProduitFini> listeBilan=this.ctr.genererBilan("entree_produit_fini");
            //System.out.println("LE NBRE : "+listeAll.size());
          /**
           * creation des Models pour la manipulation des composantes 
           */
          DefaultTableModel model=( DefaultTableModel) JtableAuj.getModel();
          DefaultTableModel modelTout=( DefaultTableModel) JtableAll.getModel();
           DefaultTableModel modelBilan=( DefaultTableModel) JtableBilan.getModel();
          /**
           * on appel les Methodes si les listes ne sont pas vide
           */
            if(liste.size()>0){
         ctr_contenuProduction.AfficherDansTableModel(liste, model,liste.get(0));
            }
           if(listeAll.size()>0){
         ctr_contenuProduction.AfficherDansTableModel(listeAll, modelTout,listeAll.get(0));
            }
             if(listeBilan.size()>0){
         ctr_contenuProduction.AfficherDansTableModel(listeBilan, modelBilan,listeBilan.get(0));
            }
        // System.out.println(liste);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        dateActuelle = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        autreDate = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        magasin = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        quantite = new javax.swing.JSpinner();
        validerProduction = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        libelle = new javax.swing.JTextField();
        genererbordereaux = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JtableAuj = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        JtableAll = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        JtableBilan = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Remplissez  Correctement les Champs", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(51, 51, 0))); // NOI18N

        jLabel2.setText("  Date");

        dateActuelle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dateActuelle.setForeground(new java.awt.Color(102, 51, 0));

        jLabel4.setText("Autre Date");

        autreDate.setDateFormatString("dd MMMM yyyy");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setText("Magasin");

        magasin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        magasin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Aucun choix" }));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 0, 0));
        jLabel6.setText("Quantite");

        validerProduction.setText("Enregister");
        validerProduction.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel7.setText("Bordereaux");

        libelle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        genererbordereaux.setText("...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(dateActuelle, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(autreDate, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(quantite)
                            .addComponent(magasin, 0, 229, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(genererbordereaux)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(validerProduction, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(218, 218, 218))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(libelle, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(dateActuelle, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(magasin, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(autreDate, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(quantite, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(libelle, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(validerProduction, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genererbordereaux, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("ENREGISTER UNE PRODUCTION");

        JtableAuj.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N°", "Date", "Quantite", "Stocks_avant", "Stocks_apres", "Bordereaux"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(JtableAuj);
        if (JtableAuj.getColumnModel().getColumnCount() > 0) {
            JtableAuj.getColumnModel().getColumn(0).setMinWidth(30);
            JtableAuj.getColumnModel().getColumn(0).setMaxWidth(35);
        }

        JtableAll.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N°", "Date", "Quantiter", "Stocks_avant", "Stocks_apres", "Magasin", "Libelle"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(JtableAll);
        if (JtableAll.getColumnModel().getColumnCount() > 0) {
            JtableAll.getColumnModel().getColumn(0).setMinWidth(30);
            JtableAll.getColumnModel().getColumn(0).setMaxWidth(35);
        }

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Toutes Les Productions Enregistres");

        JtableBilan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Quantite/Periode", "Jour", "Semaine", "Mois", "Stocks Theo."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(JtableBilan);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("               Total Productions Par Periode");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("                       Production du Jour");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(58, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(435, 435, 435)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(228, 228, 228)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(8, 8, 8)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public JDateChooser getAutreDate() {
        return autreDate;
    }

    public void setAutreDate(JDateChooser autreDate) {
        this.autreDate = autreDate;
    }

    public JLabel getDateActuelle() {
        return dateActuelle;
    }

    public void setDateActuelle(JLabel dateActuelle) {
        this.dateActuelle = dateActuelle;
    }

    public JComboBox getMagasin() {
        return magasin;
    }

    public JTextField getLibelle() {
        return libelle;
    }

    public void setLibelle(JTextField libelle) {
        this.libelle = libelle;
    }

    public JButton getGenererbordereaux() {
        return genererbordereaux;
    }

    public void setGenererbordereaux(JButton genererbordereaux) {
        this.genererbordereaux = genererbordereaux;
    }
   
    public void setMagasin(JComboBox magasin) {
        this.magasin = magasin;
    }

    public JSpinner getQuantite() {
        return quantite;
    }

    public void setQuantite(JSpinner quantite) {
        this.quantite = quantite;
    }

    public JButton getValiderProduction() {
        return validerProduction;
    }

    public void setValiderProduction(JButton validerProduction) {
        this.validerProduction = validerProduction;
    }

    public JTable getJtableAll() {
        return JtableAll;
    }

    public void setJtableAll(JTable JtableAll) {
        this.JtableAll = JtableAll;
    }

    public JTable getJtableAuj() {
        return JtableAuj;
    }

    public void setJtableAuj(JTable JtableAuj) {
        this.JtableAuj = JtableAuj;
    }

    public JTable getJtableBilan() {
        return JtableBilan;
    }

    public void setJtableBilan(JTable JtableBilan) {
        this.JtableBilan = JtableBilan;
    }
      

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JtableAll;
    private javax.swing.JTable JtableAuj;
    private javax.swing.JTable JtableBilan;
    private com.toedter.calendar.JDateChooser autreDate;
    private javax.swing.JLabel dateActuelle;
    private javax.swing.JButton genererbordereaux;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField libelle;
    private javax.swing.JComboBox magasin;
    private javax.swing.JSpinner quantite;
    private javax.swing.JButton validerProduction;
    // End of variables declaration//GEN-END:variables
}
