/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import admin.controlleur.ctr_adminSecure;
import admin.vue.adminSecure;
import classe.database;
import controller.ctr_principal;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.ScrollPaneLayout;

/**
 *
 * @author Mr_JYPY
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
     private final contenuPrincipal ct;
     private final ctr_principal ctr;
     private final String NomMagasinier;
     /**
      * constructeur prenant en parametre le Nom et Prenom du personnel connecte
      * 
      * @param NomPrenom 
      */
     public principal(String NomPrenom){
       //cette portion a permis de mettre l'icon adroite de Mon image
       Image img;
      img=getToolkit().getImage("img/LogoMc.jpg");
      // img=getToolkit().getImage(".\\img\\LogoMc.jpg");
       this.setIconImage(img);
       //end of position of icon et initialistion des composants
         initComponents();
      //ici pour les outils et avoir lecran de lutilisateur
       Toolkit outil = getToolkit();
       this.setSize(outil.getScreenSize());
       this.NomMagasinier=NomPrenom;
       ct=new contenuPrincipal(this);
       placerPanel(ct, scropMilieu);
       ctr=new ctr_principal(this);
       this.setResizable(false);
          if(database.getQuelleInstance()==1)
          {
              String message="Vous etes Connecter Via le Reseaux Locale\n"
                       + " De L'entrePrise Car Votre Connection Internet \n"
                       + " N'est pas disponible ou ne permet pas la connection\n"
                      + " Au serveur de Base de Donnee De L'entrePrise. Merci";
     JOptionPane pane = new JOptionPane(message, JOptionPane.INFORMATION_MESSAGE);
                   pane.setBackground(Color.LIGHT_GRAY);
                  pane.setIcon(null);
               //   ImageIcon imf=createImageIcon("/img/LogoMc2.jpg","image logo");
              //    pane.setIm
                  JDialog dialog = pane.createDialog(null, "Information");
                 dialog.setBackground(Color.BLACK);
                  dialog.setModal(false);
                 dialog.setVisible(true);
       }
             adminSecure.setInstance(this);
             
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel2 = new javax.swing.JPanel();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        matierePremiere = new javax.swing.JButton();
        produitFinis = new javax.swing.JButton();
        autresArticles = new javax.swing.JButton();
        deconnection = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        acceuille = new javax.swing.JButton();
        scropMilieu = new javax.swing.JScrollPane();
        barMenu = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        menuAdmin = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        utilisation = new javax.swing.JMenuItem();
        concepteur = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu3.setText("jMenu3");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jMenu4.setText("jMenu4");

        jMenuItem2.setText("jMenuItem2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jMenuItem3.setText("jMenuItem3");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AppGestion Stocks McCroft");

        jPanel1.setBackground(new java.awt.Color(164, 190, 130));
        jPanel1.setForeground(new java.awt.Color(104, 135, 10));

        matierePremiere.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        matierePremiere.setForeground(new java.awt.Color(0, 102, 0));
        matierePremiere.setText("MATIERES PREMIERES");
        matierePremiere.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        matierePremiere.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        matierePremiere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matierePremiereActionPerformed(evt);
            }
        });

        produitFinis.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        produitFinis.setForeground(new java.awt.Color(51, 51, 255));
        produitFinis.setText("PRODUITS FINIS");
        produitFinis.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        produitFinis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        autresArticles.setBackground(new java.awt.Color(255, 255, 255));
        autresArticles.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        autresArticles.setForeground(new java.awt.Color(204, 0, 51));
        autresArticles.setText("AUTRES PRODUITS");
        autresArticles.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        autresArticles.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        deconnection.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dec.jpg"))); // NOI18N
        deconnection.setToolTipText("Bouton de Fermerture de votre Application");
        deconnection.setContentAreaFilled(false);
        deconnection.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("          rubriques");
        jLabel1.setToolTipText("");

        acceuille.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        acceuille.setText("ACCEUIL");
        acceuille.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        acceuille.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(matierePremiere, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(produitFinis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(autresArticles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(acceuille, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(deconnection, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(matierePremiere, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(produitFinis, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(autresArticles, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(acceuille, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(deconnection, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        scropMilieu.setBackground(new java.awt.Color(234, 216, 216));
        scropMilieu.setViewportBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        barMenu.setBackground(new java.awt.Color(204, 204, 0));
        barMenu.setForeground(new java.awt.Color(204, 204, 0));

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/parametrage.png"))); // NOI18N

        menuAdmin.setForeground(new java.awt.Color(51, 0, 0));
        menuAdmin.setText("Administration");
        menuAdmin.setToolTipText("Page de Modification");
        jMenu5.add(menuAdmin);

        barMenu.add(jMenu5);
        barMenu.add(jMenu6);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/compte.jpg"))); // NOI18N
        barMenu.add(jMenu7);

        jMenu8.setText("A Propos");

        utilisation.setText("Manuel Utilisation");
        jMenu8.add(utilisation);

        concepteur.setText("Conception");
        jMenu8.add(concepteur);

        barMenu.add(jMenu8);

        setJMenuBar(barMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scropMilieu, javax.swing.GroupLayout.DEFAULT_SIZE, 851, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scropMilieu)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void matierePremiereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matierePremiereActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matierePremiereActionPerformed
    public static void placerPanel(JPanel panel, JScrollPane affichageCentral){
        
        JPanel panel1 = new JPanel();
        panel1.add(panel);
        
        affichageCentral.setLayout(new ScrollPaneLayout());
        affichageCentral.updateUI();
        affichageCentral.setViewportView(panel1);
        affichageCentral.updateUI();
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }
       
    public String getNomMagasinier() {
        return NomMagasinier;
    }

    public JButton getDeconnection() {
        return deconnection;
    }

    public JScrollPane getScropMilieu() {
        return scropMilieu;
    }

    public JButton getAutresArticles() {
        return autresArticles;
    }

    public JButton getMatierePremiere() {
        return matierePremiere;
    }

    public JButton getProduitFinis() {
        return produitFinis;
    }

    public JButton getAcceuille() {
        return acceuille;
    }

    public JMenuItem getConcepteur() {
        return concepteur;
    }

    public void setConcepteur(JMenuItem concepteur) {
        this.concepteur = concepteur;
    }

    public JMenuItem getUtilisation() {
        return utilisation;
    }

    public void setUtilisation(JMenuItem utilisation) {
        this.utilisation = utilisation;
    }

    public JMenuItem getMenuAdmin() {
        return menuAdmin;
    }

    public void setMenuAdmin(JMenuItem menuAdmin) {
        this.menuAdmin = menuAdmin;
    }
    
 protected  ImageIcon createImageIcon(String path,
                                           String description) {
    java.net.URL imgURL = getClass().getResource(path);
    if (imgURL != null) {
        return new ImageIcon(imgURL, description);
    } else {
        System.err.println("Couldn't find file: " + path);
        return null;
    }
}
   
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new principal().setVisible(true);
//            }
//        });
//    }
      
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceuille;
    private javax.swing.JButton autresArticles;
    private javax.swing.JMenuBar barMenu;
    private javax.swing.JMenuItem concepteur;
    private javax.swing.JButton deconnection;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JButton matierePremiere;
    private javax.swing.JMenuItem menuAdmin;
    private javax.swing.JButton produitFinis;
    private javax.swing.JScrollPane scropMilieu;
    private javax.swing.JMenuItem utilisation;
    // End of variables declaration//GEN-END:variables
}
